// Mock data + i18n strings
const I18N = {
  ru: {
    tabs: { video: 'Видео', streams: 'Стримы', news: 'Новости', assistant: 'Ассистент', settings: 'Настройки' },
    tagline: 'Транскрипты, брифы и новости — локально, без слоп-поиска.',
    videoInputPh: 'Вставь YouTube-ссылку или ID…',
    run: 'Обработать',
    running: 'Обрабатываю',
    lang: 'Язык брифа',
    model: 'Модель',
    format: 'Формат',
    backend: 'Бэкенд',
    onlyTranscript: 'Только транскрипт',
    forceRefresh: 'Обновить принудительно',
    transcript: 'Расшифровка',
    brief: 'Бриф',
    history: 'История',
    streams: 'Прямые эфиры',
    newStream: 'Новый стрим',
    activeStreams: 'Активные потоки',
    moderation: 'На модерации',
    feed: 'Лента',
    assistant: 'Ассистент',
    settings: 'Настройки',
    integrations: 'Интеграции',
    storage: 'Хранилище',
    askPlaceholder: 'Спроси что-нибудь… «как смонтировать чанки?»',
    send: 'Отправить',
    fromCache: 'из кэша',
    cost: 'стоимость',
    tokens: 'токены',
    approve: 'Одобрить',
    reject: 'Отклонить',
    reviewAll: 'Обработать всё',
    open: 'Открыть',
    close: 'Закрыть',
    source: 'Источник',
    confidence: 'Достоверность',
    duration: 'Длительность',
    channel: 'Канал',
    speaker: 'Ведущий',
    interval: 'Интервал',
    whisper: 'Whisper',
    status: 'Статус',
    chunks: 'Чанков',
    items: 'Новостей',
    pause: 'Пауза',
    resume: 'Продолжить',
    stop: 'Стоп',
    restart: 'Рестарт',
    edit: 'Ред.',
    delete: 'Удалить',
    briefNow: 'Бриф сейчас',
  },
  en: {
    tabs: { video: 'Video', streams: 'Streams', news: 'News', assistant: 'Assistant', settings: 'Settings' },
    tagline: 'Transcripts, briefs and news — local, without the AI-slop hunt.',
    videoInputPh: 'Paste a YouTube URL or video ID…',
    run: 'Run',
    running: 'Running',
    lang: 'Brief language',
    model: 'Model',
    format: 'Format',
    backend: 'Backend',
    onlyTranscript: 'Transcript only',
    forceRefresh: 'Force refresh',
    transcript: 'Transcript',
    brief: 'Brief',
    history: 'History',
    streams: 'Live streams',
    newStream: 'New stream',
    activeStreams: 'Active streams',
    moderation: 'Moderation',
    feed: 'Feed',
    assistant: 'Assistant',
    settings: 'Settings',
    integrations: 'Integrations',
    storage: 'Storage',
    askPlaceholder: 'Ask anything… “how do chunks get merged?”',
    send: 'Send',
    fromCache: 'from cache',
    cost: 'cost',
    tokens: 'tokens',
    approve: 'Approve',
    reject: 'Reject',
    reviewAll: 'Review all',
    open: 'Open',
    close: 'Close',
    source: 'Source',
    confidence: 'Confidence',
    duration: 'Duration',
    channel: 'Channel',
    speaker: 'Speaker',
    interval: 'Interval',
    whisper: 'Whisper',
    status: 'Status',
    chunks: 'Chunks',
    items: 'News items',
    pause: 'Pause',
    resume: 'Resume',
    stop: 'Stop',
    restart: 'Restart',
    edit: 'Edit',
    delete: 'Delete',
    briefNow: 'Brief now',
  },
};

// Sample transcript segments
const SAMPLE_SEGMENTS = [
  { start: 0,    text: 'Сегодня мы подключили RTX 5090 к Mac Studio через Thunderbolt 5 и сразу столкнулись с неожиданным поведением.' },
  { start: 6.2,  text: 'macOS определил карту как внешний GPU, но драйвер оказался урезанным.' },
  { start: 14.8, text: 'В Blender рендер пошёл, но только на CPU — Metal отказывался видеть CUDA-устройство.' },
  { start: 22.1, text: 'Мы попробовали Asahi Linux на M-чипе и получили совсем другую картину.' },
  { start: 31.5, text: 'Производительность в 3x выше, чем у встроенного GPU, и даже тише по шуму.' },
  { start: 41.0, text: 'Но потребление в пиковых нагрузках — 540 ватт, что для Mac-экосистемы беспрецедентно.' },
  { start: 52.3, text: 'Главный вывод: Apple не запретит, но и не поддержит — стоит готовиться к костылям.' },
  { start: 63.7, text: 'В следующем ролике разберём, как настроить ZLUDA под macOS.' },
  { start: 72.0, text: 'Подписывайтесь, ставьте колокольчик — и до встречи.' },
];

const SAMPLE_BRIEF_SECTIONS = [
  {
    title: 'Суть',
    body: 'Эксперимент с подключением RTX 5090 к Mac Studio через Thunderbolt 5. macOS видит карту, но драйверная поддержка неполная. Asahi Linux даёт рабочий путь с 3× приростом, но с риском 540 Вт пиков.',
  },
  {
    title: 'Ключевые идеи',
    body: '— Thunderbolt 5 физически подключает eGPU, но Metal не видит CUDA.\n— Asahi Linux снимает ограничения: работают CUDA 12 и ZLUDA.\n— Шум ниже встроенного GPU за счёт большего радиатора.\n— Потребление — лимитирующий фактор для типовых БП.',
  },
  {
    title: 'Факты и цифры',
    body: '• 3× прирост на Blender Cycles против M2 Ultra.\n• Пик 540 Вт на сцене BMW-Cycles.\n• Thunderbolt 5: 80 Gbps, достаточно для PCIe 4.0 ×4.\n• ZLUDA-драйвер: open-source, MIT.',
  },
  {
    title: 'Применение',
    body: 'Может быть актуально для студий 3D-рендера, которые не готовы уходить с экосистемы macOS, но хотят CUDA-ускорение локально без облака.',
  },
  {
    title: 'Черновик ТЗ',
    body: '**Цель**: сделать тулкит настройки RTX-eGPU на Mac.\n\n**MVP**: скрипт установки ZLUDA, проверка Thunderbolt-подключения, бенчмарк.\n\n**Риски**: Apple может закрыть Thunderbolt-туннелирование в следующих версиях macOS.',
  },
];

const SAMPLE_VIDEOS = [
  { id: 'C4KWsmezXm4', title: 'Подключил RTX 5090 к Mac — и не ожидал такого', duration: 842, language: 'ru', briefs: 2, cost: 0.0847, date: '19 апр', dateEn: 'Apr 19' },
  { id: 'lH5wrfNwL3k', title: 'Claude изменил фондовый рынок навсегда — туториал', duration: 1523, language: 'en', briefs: 1, cost: 0.1120, date: '18 апр', dateEn: 'Apr 18' },
  { id: 'mssPkDuQnmY', title: 'Как построить свой Claude-ассистент для трейдинга', duration: 1187, language: 'en', briefs: 3, cost: 0.2341, date: '17 апр', dateEn: 'Apr 17' },
  { id: 'z5u1jPKz0YQ', title: 'Open-source код ВСЁ?', duration: 634, language: 'ru', briefs: 1, cost: 0.0520, date: '15 апр', dateEn: 'Apr 15' },
  { id: 'xQyL4k2s', title: 'Postgres 18: что нового и зачем это знать', duration: 921, language: 'en', briefs: 2, cost: 0.0932, date: '14 апр', dateEn: 'Apr 14' },
  { id: 'qpLmn93d', title: 'Discovery-сессия: что спросить у команды на старте', duration: 2340, language: 'ru', briefs: 1, cost: 0.1804, date: '12 апр', dateEn: 'Apr 12' },
];

const SAMPLE_STREAMS = [
  {
    id: 'str_bloomberg_live',
    url: 'https://www.youtube.com/watch?v=iEpJwprxDdk',
    channel: 'Bloomberg Live',
    speaker: 'Tom Keene',
    status: 'active',
    running: true,
    intervalMin: 3,
    whisper: 'distil-large-v3',
    chunksTotal: 47,
    itemsCount: 23,
    language: 'en',
    cost: 0.84,
    uptime: '2ч 21мин',
    uptimeEn: '2h 21m',
    spark: [2,4,3,5,8,6,7,5,9,7,8,6,9,11,8,10,12],
  },
  {
    id: 'str_rbc_news',
    url: 'https://www.youtube.com/watch?v=FK3dav4bA4s',
    channel: 'РБК',
    speaker: null,
    status: 'active',
    running: true,
    intervalMin: 5,
    whisper: 'medium',
    chunksTotal: 12,
    itemsCount: 8,
    language: 'ru',
    cost: 0.21,
    uptime: '58мин',
    uptimeEn: '58m',
    spark: [1,2,2,3,3,4,5,4,6,5,7,6,8],
  },
  {
    id: 'str_cnn_world',
    url: 'https://www.youtube.com/watch?v=w_Ma8oQLmSM',
    channel: 'CNN Breaking',
    speaker: 'Anderson Cooper',
    status: 'paused',
    running: false,
    intervalMin: 2,
    whisper: 'small',
    chunksTotal: 140,
    itemsCount: 62,
    language: 'en',
    cost: 1.46,
    uptime: '5ч 12мин',
    uptimeEn: '5h 12m',
    spark: [3,4,5,4,6,5,7,6,8,5,6,4,3,2,1,1,2],
  },
];

const SAMPLE_NEWS = [
  {
    id: 101, status: 'draft',
    headline: 'ФРС намекнула на паузу в повышении ставки до конца 2026 года',
    quote: 'We see a clear path to neutral by year-end — but we are not there yet.',
    category: 'finance',
    tags: ['fed', 'rates', 'macro'],
    source: 'Bloomberg Live', speaker: 'Tom Keene',
    time: '14:23', duration: '0:42', confidence: 0.92,
    concept: 'central bank pause',
    isDuplicate: false,
  },
  {
    id: 102, status: 'draft',
    headline: 'Tesla отзывает 240 000 машин из-за уязвимости в автопилоте',
    quote: 'It\'s a software update, not a hardware recall — but we are taking it seriously.',
    category: 'tech',
    tags: ['tesla', 'recall', 'autopilot'],
    source: 'Bloomberg Live', speaker: 'Tom Keene',
    time: '14:08', duration: '1:04', confidence: 0.88,
    concept: 'vehicle recall',
    isDuplicate: false,
  },
  {
    id: 103, status: 'draft',
    headline: 'Anthropic выпустила новую модель Claude для финансов',
    quote: 'Это первая модель, специально обученная на SEC-отчётности и bloomberg-ленте.',
    category: 'ai',
    tags: ['anthropic', 'claude', 'finance'],
    source: 'РБК', speaker: null,
    time: '13:54', duration: '0:38', confidence: 0.81,
    concept: 'ai model release',
    isDuplicate: true, dupSim: 0.89,
  },
  {
    id: 104, status: 'draft',
    headline: 'ЕС вводит углеродный налог на импорт стали с июля',
    quote: 'Это крупнейшая климатическая мера за последние пять лет.',
    category: 'policy',
    tags: ['eu', 'carbon', 'trade'],
    source: 'РБК', speaker: null,
    time: '13:41', duration: '0:51', confidence: 0.94,
    concept: 'carbon tax',
    isDuplicate: false,
  },
  {
    id: 105, status: 'approved',
    headline: 'OpenAI подтвердила приобретение Anysphere за $3 млрд',
    quote: 'We will integrate Cursor as a first-party product.',
    category: 'tech',
    tags: ['openai', 'acquisition', 'dev-tools'],
    source: 'Bloomberg Live', speaker: 'Tom Keene',
    time: '12:18', duration: '1:22', confidence: 0.96,
    concept: 'tech acquisition',
    isDuplicate: false,
  },
  {
    id: 106, status: 'approved',
    headline: 'Nvidia анонсировала следующее поколение Blackwell Ultra',
    quote: 'Our pace of innovation is now quarterly, not annually.',
    category: 'tech',
    tags: ['nvidia', 'gpu', 'blackwell'],
    source: 'Bloomberg Live', speaker: 'Tom Keene',
    time: '11:55', duration: '0:58', confidence: 0.93,
    concept: 'gpu announcement',
    isDuplicate: false,
  },
];

const CATEGORY_COLORS = {
  finance:  { bg: 'oklch(0.95 0.04 75)',  fg: 'oklch(0.42 0.14 75)'  },
  tech:     { bg: 'oklch(0.95 0.03 265)', fg: 'oklch(0.40 0.15 265)' },
  ai:       { bg: 'oklch(0.94 0.05 155)', fg: 'oklch(0.40 0.13 155)' },
  policy:   { bg: 'oklch(0.95 0.03 25)',  fg: 'oklch(0.42 0.16 25)'  },
  science:  { bg: 'oklch(0.95 0.03 195)', fg: 'oklch(0.40 0.14 195)' },
  sports:   { bg: 'oklch(0.95 0.04 140)', fg: 'oklch(0.40 0.13 140)' },
  other:    { bg: 'oklch(0.95 0.01 90)',  fg: 'oklch(0.40 0.03 90)'  },
};

const INTEGRATIONS = [
  { id: 'supadata', name: 'Supadata', kind: 'cloud', desc: 'Транскрипты YouTube', descEn: 'YouTube transcripts', configured: true, masked: 'sup_…k9f2', website: 'supadata.ai' },
  { id: 'anthropic', name: 'Anthropic Claude', kind: 'cloud', desc: 'Генерация брифов и новостей', descEn: 'Briefs and news extraction', configured: true, masked: 'sk-ant-…a1b2', website: 'console.anthropic.com' },
  { id: 'openai', name: 'OpenAI', kind: 'cloud', desc: 'Embeddings для дедупа', descEn: 'Embeddings for deduplication', configured: true, masked: 'sk-proj-…c3d4', website: 'platform.openai.com' },
  { id: 'pexels', name: 'Pexels', kind: 'cloud', desc: 'Фото-иллюстрации к новостям', descEn: 'Stock photos for news', configured: false, masked: null, website: 'pexels.com' },
  { id: 'fastembed', name: 'fastembed', kind: 'local', desc: 'Локальные ONNX-эмбеддинги', descEn: 'Local ONNX embeddings', configured: true, website: 'github.com/qdrant/fastembed' },
  { id: 'ollama', name: 'Ollama', kind: 'local', desc: 'Локальные модели', descEn: 'Local LLM runner', configured: false, website: 'ollama.ai' },
];

const ASSISTANT_MESSAGES_INIT = [
  { role: 'assistant', text: 'Я знаю про пайплайн, БД, настройки и коды ошибок. Спроси что-то — или попроси сделать.' },
  { role: 'user', text: 'Почему последний стрим завис на чанке 47?' },
  { role: 'assistant', text: 'Посмотрел. Чанк 47 в Bloomberg Live застрял в статусе `transcribing` уже 8 минут. Это выше нормы (~30с на 2-мин чанк).\n\nПохоже на нехватку VRAM: при модели `distil-large-v3` на RTX 2060 (6GB) иногда случается OOM. В логах вижу `CUDA out of memory`.\n\nХочешь я переключу этот стрим на `medium` и рестартну обработку застрявших чанков?', hasAction: true },
];

Object.assign(window, {
  I18N, SAMPLE_SEGMENTS, SAMPLE_BRIEF_SECTIONS,
  SAMPLE_VIDEOS, SAMPLE_STREAMS, SAMPLE_NEWS,
  CATEGORY_COLORS, INTEGRATIONS, ASSISTANT_MESSAGES_INIT,
});
